### ISSUE TITLE
Passing ROS2 Build Farm for ROS Humble

### ISSUE THREAD

**Issue by KeplerC** [BerkeleyAutomation/FogROS2#67]
This ticket keeps track of the progress of passing ROS2 build farm for ROS humble. 

- [x] passing colcon test 
   - [x]  passing `colcon test` (#63) 

- [x] passing build farm tests 
   - [x] test_copyright for fogros2  (#64)
   - [x] test_copyright for fogros2_examples (#64)
   - [x] test_flake8 for fogros2 (#65)
   - [x] test_flake8 for fogros2_examples (#65)
   - [x] test_pep257 for fogros2 (#66)
   - [x] test_pep257 for fogros2_examples (#66)

**Comment by mjd3** [comment]
Should be resolved by #74
